config/routes.rb
Rails.application.routes.draw do

  get 'about' => 'pages#about'

  get 'contact' => 'pages#contact'

  resources :spots, only: [:index, :show, :edit, :update]

  root 'pages#home'

end

app/models/spot.rb
class Spot < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def about
  end

  def contact
  end

  def home
    @date = Time.now
    @places = places

    @spot = Spot.all.sample
  end

  def places
   ["Havana", "Belga", "Monk", "Delirium"]
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  before_action :set_spot, only: [:edit, :update, :show]

  def index
    @spots = Spot.all
  end

  def show
  end

  def edit
  end

  def update
    @spot.update(spot_params)
    redirect_to @spot
  end

  private

  def set_spot
    @spot = Spot.find(params[:id])
  end


  def spot_params
    params.require(:spot).permit(:name, :zip, :rating)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Letsparty</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- Leave those next 4 lines if you care about users using IE8 -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->



  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Team Jacnut-Brands inc.</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "About", about_path %></li>
        <li class="active"><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">

<%= yield %>

    </div>
  </div>
</div>

    <!-- Including Bootstrap JS (with its jQuery dependency) so that dynamic components work -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

</body>
</html>

app/views/pages/about.html.erb
<h1>These are the party guys</h1>
<ul>
  <li><img src="../../assets/images/thomas.jpeg">Tomasz</li>
  <li><img src="../../assets/images/philip.jpeg">Philip</li>
  <li><img src="../../assets/images/alvarito.gif">Alvaro</li>
</ul>

app/views/pages/contact.html.erb
<h1>Contact the party guys here!</h1>


<form>
  <div class="form-group">
    <label for="exampleInputEmail1">email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">question</label>
    <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Question">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/pages/home.html.erb
<h1>Date </h1>
<p>Today we are ... </p>
<%= @date %>
<br>
<%= @places.sample %>
<p>
"This is today's spot" : <%= @spot.name %></p>

app/views/spots/edit.html.erb
<h1>Updating spot</h1>
<%= form_for @spot do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :zip %>
  <%= f.text_field :zip %>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
  <%= f.submit "Submit" %>
<% end %>

app/views/spots/index.html.erb
<ul>
  <% @spots.each do |beer| %>
  <li>
    <%= link_to beer.name, spot_path(beer)%>
    <%=  beer.rating.to_s + " " + beer.zip %>
  </li>
  <% end %>
</ul>

app/views/spots/show.html.erb
<h2><%= @spot.name %></h2>